### ISSUE TITLE
Naggyv2 Fails to Install on 10.14 b9

### ISSUE THREAD

**Issue by gmarnin** [erikng/mdmscripts#1]
I used `munkipkg` to build `Naggy-2.0`, leaving all default setting in `build-info.json`
It fails to install on b9

```12mor101m2:~ itsadmin2$ sudo installer -verboseR -pkg /Users/itsadmin2/Desktop/naggyv2/build/Naggy-2.0.pkg -target /
installer: Package name is 
installer: Installing at base path /
installer:PHASE:Preparing for installation…
installer:PHASE:Preparing the disk…
installer:PHASE:Preparing …
installer:PHASE:Waiting for other installations to complete…
installer:PHASE:Configuring the installation…
installer:STATUS:
installer:%83.101192
installer:PHASE:Running package scripts…
installer:PHASE:Validating packages…
installer:%97.750000
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
12mor101m2:~ itsadmin2$ sw_vers
ProductName:    Mac OS X
ProductVersion:    10.14
BuildVersion:    18A377a
```

I got it to run after I ran `sudo mkdir "/Library/Application Support/naggy/Logs"`
```
/Users/itsadmin2/Desktop/naggyv2/scripts/postinstall 
Traceback (most recent call last):
  File "/Users/itsadmin2/Desktop/naggyv2/scripts/postinstall", line 69, in <module>
    main()
  File "/Users/itsadmin2/Desktop/naggyv2/scripts/postinstall", line 41, in main
    os.chmod(naggy_log_path, 0o777)
OSError: [Errno 2] No such file or directory: '/Library/Application Support/naggy/Logs'
12mor101m2:~ itsadmin2$ 
12mor101m2:~ itsadmin2$ 
12mor101m2:~ itsadmin2$ 
12mor101m2:~ itsadmin2$ mkdir "/Library/Application Support/naggy/Logs"
mkdir: /Library/Application Support/naggy/Logs: Permission denied
12mor101m2:~ itsadmin2$ 
12mor101m2:~ itsadmin2$ sudo mkdir "/Library/Application Support/naggy/Logs"
Password:
12mor101m2:~ itsadmin2$ /Users/itsadmin2/Desktop/naggyv2/scripts/postinstall 
Traceback (most recent call last):
  File "/Users/itsadmin2/Desktop/naggyv2/scripts/postinstall", line 69, in <module>
    main()
  File "/Users/itsadmin2/Desktop/naggyv2/scripts/postinstall", line 41, in main
    os.chmod(naggy_log_path, 0o777)
OSError: [Errno 1] Operation not permitted: '/Library/Application Support/naggy/Logs'
12mor101m2:~ itsadmin2$ 
12mor101m2:~ itsadmin2$ 
12mor101m2:~ itsadmin2$ sudo /Users/itsadmin2/Desktop/naggyv2/scripts/postinstall 
12mor101m2:~ itsadmin2$ 
```

**Comment by erikng** [comment]
Thanks. Good ol' git is getting in the way here. Need to think about what I want to do.

**Comment by erikng** [comment]
Addressed https://github.com/erikng/mdmscripts/commit/1ce0c3966c94bcdab484b8a7013a8ecf5652cba8 and https://github.com/erikng/mdmscripts/commit/39f818c8247477306758d4b2d9c189c76b7e28a1

In order to create a properly working package, you will need to run the following command:
`munkipkg --sync /path/to/cloned_repo/dep/tools/naggyv2` to load the Bom.txt file I created.
